### PR TITLE
Display tags under `gita ll`

### LINKED ISSUE #117: Optionally display tags
it could be one of the information items

spun from #114

### PR DESCRIPTION
**Pull request by nwu63**
Closes #117. The git command is taken from [this answer](https://stackoverflow.com/a/18660163). Again since this is a shell script I had to set `shell=True` here and also get rid of the `.split()`.

There are two things I noticed:
- the colour for tags when running `gita ll` is white, I'm guessing because it didn't fit any of the other categories? Just want to check that this is the desired behaviour
- the "info" column does not have fixed width, so the table is not well-aligned. Given that this is implemented as an iterator, I'm not sure how to best do this. If you can suggest an implementation I can throw that in this PR, otherwise it could also be a separate development

### CODE REVIEW

**Comment by nosarthur** [comment]
For the 1st point, I think it may make more sense to assign a new color to tag.

I actually don't quite get your second point, can you show me a screenshot?

**Comment by nwu63** [comment]
That sounds good.

This is what I mean:
Screenshot_20210118_170058

The 2nd column does not have fixed width so things are not aligned well.

**Comment by nosarthur** [comment]
I actually deliberately left that unaligned. If the branch name is very long and they are aligned, there would be a lot of blank spaces, and it would be hard to see the correspondence of the commit message

**Comment by nwu63** [comment]
That's a good point actually, since there's no need to compare across rows for that. I guess for this PR the only thing remaining is to select a new colour for the tag?

**Comment by nosarthur** [comment]
yeah. 

I can also just merge this PR in and worry about that later. What do you think?

https://github.com/nosarthur/gita/blob/master/gita/utils.py#L202

**Comment by nwu63** [comment]
Entirely your call, I'm happy with this PR as is but I do think it would be better to eventually have a separate colour.

**Comment by nosarthur** [comment]
released in v0.12.9 
thanks for the contribution!

**Comment by nwu63** [comment]
Thanks for working on this project!

**Pull request merged**
