### PR TITLE
Add now option: gita ll --show-paths

### PR DESCRIPTION
**Pull request by xsteve**
I have a lot of checked out repositories on my machine
gita ll does not yet include the disk location

This commit adds the option --show-paths to show the paths as well

### CODE REVIEW

**Comment by nosarthur** [comment]
What do you use the disk path information for?

Repo path can be displayed using `gita ls repo-name`, would this be enough?

I typically use the following command in terminal to go to a repo's directory without even looking at the path.

```
cd `gita ls repo-name`
```

**Comment by xsteve** [comment]
I know about gita ls repo-name

My intended workflow is to use an alias (e.g. gll) to run gita ll --show-paths
That way I get a list of all my registered git repos and working directories.

The output is useful for me. I copy it by double clicking and use the file path to open it in an editor.

gita gives me already a nice list of the repositories. What I want to do is to work with them. Therefore I need the working directory.

**Comment by nosarthur** [comment]
Would this shell script work for your need?

```
#!/bin/sh                                                                          
          
IFS=                                                                       
gita ll | while read -r x                                                          
do                                                                                 
    echo $x                                                                        
    echo '\t'$(gita ls ${x%% *})                                                   
done      
```
You can for example save it as the `gll` command. 

Since `gita ls <repo-name>` displays the repo path, I don't see the necessity to add the `--show-path` option.

**Comment by xsteve** [comment]
Well it is your tool. Of course I can add my own scripting layer to see the information that I want to see.
I will do this.

My idea was to use gita ll to show all useful information. The repository path is useful for me almost every time. You have different work flows than I have. That is o.k.

**Comment by nosarthur** [comment]
I will refactor the code to allow user customize the `gita ll` display. Maybe let the user define their own functions that return string, and load them as a plugin

**Comment by xsteve** [comment]
Thanks - I like that idea. It is a lot more general than my proposed idea.

I am looking forward to your implementation.

**Comment by nosarthur** [comment]
please see #59 WIP

**Comment by nosarthur** [comment]
hi, @xsteve , with #59 checked in now,  to achieve what you had in mind, you can add a configuration file `info.yml` at `$XDG_CONFIG_HOME/gita/` folder (mostly likely `~/.config/gita/`) with the following content:

```
- branch
- commit_msg
- path
```

**Comment by xsteve** [comment]
Thanks - I have tested your improvement. It works for me :-)

**Pull request closed without merging**
