### PR TITLE
Add new sub command "show" to "group"

### PR DESCRIPTION
**Pull request by franzs**
This command shows the repos in a given group.

### CODE REVIEW

**Comment by nosarthur** [comment]
maybe add an argument to `gita group ll`?

**Comment by franzs** [comment]
Hi Dong Zhou ,
this is something I considered, too. For me showing the content of a group doesn't fit to `gita group ll` or `gita group ls`. Similar to `ls` on the command line I would expect `gita group ll group1` to list "group1" only - including the group name, e. g.
```shell
$ gita group ll group1
group1: repo1 repo2
```

**Comment by nosarthur** [comment]
I am hesitant to add another keyword whose behavior is so similar to `gita group ll group1`. Would that output work for you? 

Alternatively, we could make a special rule that if only 1 group is specified, omit the group name. What do you think?

**Comment by franzs** [comment]
Hi Dong Zhou,
there is an implemenation for an optional argument to `group ll` in a new PR:
https://github.com/nosarthur/gita/pull/172
Please have a look at it.

**Comment by nosarthur** [comment]
will do, thanks

**Pull request closed without merging**
